### ISSUE TITLE
Generating INI from CSV

### ISSUE THREAD

**Issue by lawremi** [reteo/Sprocket#11]
Hi Reteo,

I've managed to get the table out of ODS and into a semi-colon-separated CSV. The sprocket-csv script appears to generate a valid INI with distribution settings. However, my understanding is that it Sprocket also needs mod definitions. Are those available anywhere?

**Comment by reteo** [comment]
Actually, what the sprocket-csv script creates is a list of distributions for pasting into Sprocket INI files.  Those need to be made by hand, and the instructions for making them is on the main page of this site, under "INI Format", "Mod Definition."  With the exception of the "Detect" setting (which requires the modID), you decide what to use for the other settings, as long as they don't use fancy characters.

**Comment by lawremi** [comment]
I see.  Do those "example" INI files represent what is currently included with COG, and the spreadsheet? Or do I need to manually update all of them?

**Comment by reteo** [comment]
They updated as frequently as I updated COG, just to be sure that changes in the spreadsheet and sprocket's code were correctly represented.

**Comment by lawremi** [comment]
Great. Thanks for your help.

**Comment by reteo** [comment]
No problem!
