### ISSUE TITLE
question UBC

### ISSUE THREAD

**Issue by SvEgiiVEteR** [reteo/Sprocket#4]
UndergroundBiomesConstructs
question I'd better make a separate configuration or can it?
Replaces: minecraft:stone, UndergroundBiomes:igneousStone, UndergroundBiomes:metamorphicStone, UndergroundBiomes:sedimentaryStone

for configs to work with the UBC or without the UBC

**Comment by reteo** [comment]
UBC makes use of a lot of different types of stone that are not oredicted.  There's no way that I know of to reliably place ores in UBC biomes without slowing the game down to a crawl.

**Comment by SvEgiiVEteR** [comment]
Yes UBC biomes will be broken
but not normal stones in the world and it's good.

I found only 3 block name.
Now I have created a new configs with
Replaces: UndergroundBiomes:igneousStone, UndergroundBiomes:metamorphicStone, UndergroundBiomes:sedimentaryStone
and when I remove UBC I change the config COG
it's a little bit of a hindrance.

my question is: if I create a universal config adding to minecraft:stone

Replaces: minecraft:stone, UndergroundBiomes:igneousStone, UndergroundBiomes:metamorphicStone, UndergroundBiomes:sedimentaryStone

it will work without the UBC?
without any problems?
or better to use different config files?

**Comment by reteo** [comment]
I don't know anything about Underground Biomes.  I'm afraid I can't really answer that one.

**Comment by SvEgiiVEteR** [comment]
oh my bad english ((
I'm about. the presence of the blocks in the configuration:
 Replaces: minecraft:stone, UndergroundBiomes:igneousStone, UndergroundBiomes:metamorphicStone, UndergroundBiomes:sedimentaryStone
that is currently not in the game, will not cause problems?

**Comment by reteo** [comment]
You can try.  You'll have to test it to see if it works.  But keep in mind the more "replaces" you add, the slower the game will get.
