### ISSUE TITLE
Railcraft Abyssal Ores

### ISSUE THREAD

**Issue by SvEgiiVEteR** [reteo/Sprocket#5]
found an error
COG does not remove Railcraft: cube: 6
the world oldest generation from mod(no ore) and of the new Railcraft.ini (with ore)

**Comment by reteo** [comment]
If the world was already generated, then the existing generated ore won't be removed.

**Comment by SvEgiiVEteR** [comment]
No, I'm serious.
incorrect configuration is not deleted ailcraft:cube:6

**Comment by reteo** [comment]
I am going to need the full log; there isn't enough information here for me to figure out the source of the problem.

**Comment by SvEgiiVEteR** [comment]
your Railcraft.ini, does not remove Railcraft:cube:6

For this reason, the mod Railcraft created Abyssal, and they are not removed from the world.+ COG created Abyssal

They remain in the world(Abyssal)from Railcraft. But without ore. because the ore  removed in Railcraft.ini
there is seen that in the list:
https://gist.github.com/SvEgiiVEteR/40bf26601f5b4b04b7b15f6e76d3d2c2
no block Railcraft:cube:6

**Comment by reteo** [comment]
If you do not provide the actual game log, I am unable to help you.  All you're linking to is a small part of the XML file, and I do not have enough information to know what is _causing_ the problem.

**Comment by SvEgiiVEteR** [comment]
This piece RailCraft.xml it yours. 702 line

**Comment by reteo** [comment]
Ah, I see what you mean now.  I apologize, but sometimes your way of speaking is extremely difficult to follow.

**Comment by SvEgiiVEteR** [comment]
I understand that it is difficult, I do not know much English (((

**Comment by reteo** [comment]
Okay, it looks like it's working correctly now.

**Comment by SvEgiiVEteR** [comment]
Thank you is now all is well)

https://github.com/reteo/Sprocket/commit/6ee9e1d45481dd9b13f1aa9fb4da591279114930
and for these changes, ini file does not exist?

**Comment by reteo** [comment]
What do you mean?  The issue was in Sprocket itself, not the INI file.

**Comment by SvEgiiVEteR** [comment]
ThermalFoundation.xml file you edited yourself.
sprocket.py does not change the file as you
I checked
cmd `sprocket.py ThermalFoundation.ini`

**Comment by reteo** [comment]
Actually, ThermalFoundation.xml was an update I updated a couple weeks ago that I had forgotten to upload.  That had nothing to do with the update to sprocket and Railcraft.xml.

**Comment by SvEgiiVEteR** [comment]
@reteo Yes I understand and know.
I just do not find these changes in my file
... Maybe I'm a little bit to change the file, this does not find the changed lines
I'm sorry to trouble you).

**Comment by reteo** [comment]
What file are you referring to?

**Comment by SvEgiiVEteR** [comment]
ThermalFoundation.ini

**Comment by reteo** [comment]
What changes did you not find in ThermalFoundation.ini?

**Comment by SvEgiiVEteR** [comment]
such example.
https://github.com/reteo/Sprocket/commit/876ac7b2a7fdf7284565f5718fa8116f2bdcc8f5#diff-8803353293e8912e996235b05b77301eR259
I checked all is well
Applied Energistics.xml coincides with mine.

**Comment by reteo** [comment]
That change was due to the fix for #3; the bug was in sprocket.py, not any of the INI files.
